name: Build, Lint, Test

on: workflow_call

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Dependencies
        id: cache-cargo
        uses: actions/cache@v3
        env:
          cache-name: cache-cargo-deps
        with:
          path: ./target/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        name: Build Dependencies
        run: ./install_deps.sh
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy --all-targets --all-features
      - name: Test
        run: cargo test --verbose
